name:  Generate_SBOM_Docker

on: 
  #push:
  workflow_dispatch:
  
jobs:
  scribe-report-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    
    - name: Generate cyclonedx json SBOM
      id: valiant_json
      uses: scribe-security/action-bom@master
      with:
        #type: git
        target: docker:mongo-express
        format: json
        scribe-enable: true
        scribe-client-id: ${{ secrets.clientid }}
        scribe-client-secret: ${{ secrets.clientsecret }}
        product-key: Mongo-Express
        
    - uses: actions/upload-artifact@v2
      with:
          name: scribe-sbom
          path: ${{ steps.valiant_json.outputs.OUTPUT_PATH }}

    - name: Generate SLSA provenance statement
      id: valint_slsa_statement
      uses: scribe-security/action-bom@master
      with:
        target: docker:mongo-express
        format: statement-slsa
        scribe-enable: true
        scribe-client-id: ${{ secrets.clientid }}
        scribe-client-secret: ${{ secrets.clientsecret }}
        product-key: Mongo-Express
          
    - uses: actions/upload-artifact@v2
      with:
        name: provenance
        path: ${{ steps.valint_slsa_statement.outputs.OUTPUT_PATH }}
        
    - name: valint verify
      id: valint_slsa_attest
      uses: scribe-security/action-bom@master
      with:
        target: docker:mongo-express
        format: attest-slsa
        scribe-enable: true
        scribe-client-id: ${{ secrets.clientid }}
        scribe-client-secret: ${{ secrets.clientsecret }}
        product-key: Mongo-Express
      
    - uses: actions/upload-artifact@v2
      with:
        name: attest
        path: ${{ steps.valint_slsa_attest.outputs.OUTPUT_PATH }}
